# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdminLogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adminLogin(self):
    self.driver.get("http://localhost:5000/auth/login")
    self.driver.find_element(By.NAME, "email").send_keys("admin@example.com")
    self.driver.find_element(By.NAME, "password").send_keys("adminpassword")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
